/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,jsx}",
  ],
  theme: {
    extend: {
      colors: {
        'bg-primary':                '#121212',
        'bg-card':                   '#2D2D2D',
        'accent':                    '#FF6B00',
        // Stitch design tokens
        'primary-container':         '#ff6b00',
        'on-primary-container':      '#572000',
        'primary':                   '#ffb693',
        'primary-fixed':             '#ffdbcc',
        'primary-fixed-dim':         '#ffb693',
        'on-primary':                '#561f00',
        'on-primary-fixed':          '#351000',
        'on-primary-fixed-variant':  '#7a3000',
        'secondary':                 '#c8c6c5',
        'secondary-container':       '#474746',
        'secondary-fixed':           '#e5e2e1',
        'secondary-fixed-dim':       '#c8c6c5',
        'on-secondary':              '#303030',
        'on-secondary-container':    '#b7b5b4',
        'on-secondary-fixed':        '#1b1b1c',
        'on-secondary-fixed-variant':'#474746',
        'tertiary':                  '#c8c6c6',
        'tertiary-container':        '#9a9999',
        'tertiary-fixed':            '#e4e2e1',
        'tertiary-fixed-dim':        '#c8c6c6',
        'on-tertiary':               '#303030',
        'on-tertiary-container':     '#313131',
        'on-tertiary-fixed':         '#1b1c1c',
        'on-tertiary-fixed-variant': '#474747',
        'background':                '#131313',
        'surface':                   '#131313',
        'surface-dim':               '#131313',
        'surface-bright':            '#393939',
        'surface-variant':           '#353534',
        'surface-container-lowest':  '#0e0e0e',
        'surface-container-low':     '#1c1b1b',
        'surface-container':         '#201f1f',
        'surface-container-high':    '#2a2a2a',
        'surface-container-highest': '#353534',
        'on-surface':                '#e5e2e1',
        'on-surface-variant':        '#e2bfb0',
        'on-background':             '#e5e2e1',
        'outline':                   '#a98a7d',
        'outline-variant':           '#5a4136',
        'error':                     '#ffb4ab',
        'error-container':           '#93000a',
        'on-error':                  '#690005',
        'on-error-container':        '#ffdad6',
        'inverse-surface':           '#e5e2e1',
        'inverse-on-surface':        '#313030',
        'inverse-primary':           '#a04100',
        'surface-tint':              '#ffb693',
      },
      fontFamily: {
        inter:        ['Inter', 'sans-serif'],
        h1:           ['Space Grotesk', 'sans-serif'],
        h2:           ['Space Grotesk', 'sans-serif'],
        'body-md':    ['Inter', 'sans-serif'],
        'body-lg':    ['Inter', 'sans-serif'],
        'mono-data':  ['Inter', 'sans-serif'],
        'label-caps': ['Space Grotesk', 'sans-serif'],
      },
      fontSize: {
        h1:          ['32px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '700' }],
        h2:          ['24px', { lineHeight: '1.3', letterSpacing: '-0.01em', fontWeight: '600' }],
        'body-md':   ['16px', { lineHeight: '1.5',  fontWeight: '400' }],
        'body-lg':   ['18px', { lineHeight: '1.6',  fontWeight: '400' }],
        'mono-data': ['14px', { lineHeight: '1.4',  letterSpacing: '0em',    fontWeight: '500' }],
        'label-caps':['12px', { lineHeight: '1',    letterSpacing: '0.05em', fontWeight: '700' }],
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg:      '0.25rem',
        xl:      '0.5rem',
        full:    '0.75rem',
      },
      spacing: {
        base:               '4px',
        xs:                 '8px',
        sm:                 '12px',
        md:                 '16px',
        lg:                 '24px',
        xl:                 '40px',
        gutter:             '16px',
        'container-margin': '24px',
      },
    },
  },
  plugins: [],
}
